
// SPDX-License-Identifier: Apache-2.0.
//---------------------------------------------------------------------------//
// Copyright (c) 2023 Generated by ZKLLVM-transpiler
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//---------------------------------------------------------------------------//
pragma solidity >=0.8.4;

import "@nilfoundation/evm-placeholder-verification/contracts/types.sol";
import "@nilfoundation/evm-placeholder-verification/contracts/basic_marshalling.sol";
import "@nilfoundation/evm-placeholder-verification/contracts/interfaces/modular_gate_argument.sol";
import "hardhat/console.sol";


contract modular_gate_argument_gates is IGateArgument{
    uint256 constant modulus = 28948022309329048855892746252171976963363056481941560715954676764349967630337;

    // Append commitments
    function verify(
        bytes calldata blob,
        uint256 theta
    ) external view returns (uint256 F){
        uint256 theta_acc = 1;
        uint256 eval;

		uint256 sum;
		uint256 prod;
		uint256 gate;
/* -- gate 0 is inlined -- */
		gate = 0;
		sum = 0;
		prod = 28948022309329048855892746252171976963363056481941560715954676764349967630336;
		prod = mulmod(prod, basic_marshalling.get_uint256_be(blob, 2624), modulus);
		sum = addmod(sum, prod, modulus);
		prod = basic_marshalling.get_uint256_be(blob, 2592);
		sum = addmod(sum, prod, modulus);
		prod = basic_marshalling.get_uint256_be(blob, 2560);
		sum = addmod(sum, prod, modulus);
		gate = addmod(gate, mulmod(theta_acc, sum, modulus), modulus);
		theta_acc = mulmod(theta_acc, theta, modulus);
		gate = mulmod(gate, basic_marshalling.get_uint256_be(blob, 320), modulus);
		F = addmod(F, gate, modulus);

/* -- gate 1 is inlined -- */
		gate = 0;
		sum = 0;
		prod = 28948022309329048855892746252171976963363056481941560715954676764349967630336;
		prod = mulmod(prod, basic_marshalling.get_uint256_be(blob, 2656), modulus);
		sum = addmod(sum, prod, modulus);
		prod = basic_marshalling.get_uint256_be(blob, 2656);
		prod = mulmod(prod, basic_marshalling.get_uint256_be(blob, 2656), modulus);
		sum = addmod(sum, prod, modulus);
		gate = addmod(gate, mulmod(theta_acc, sum, modulus), modulus);
		theta_acc = mulmod(theta_acc, theta, modulus);
		sum = 0;
		prod = 28948022309329048855892746252171976963363056481941560715954676764349967630336;
		sum = addmod(sum, prod, modulus);
		prod = basic_marshalling.get_uint256_be(blob, 2656);
		sum = addmod(sum, prod, modulus);
		prod = 28948022309329048855892746252171976963363056481941560715954676764349967630336;
		prod = mulmod(prod, basic_marshalling.get_uint256_be(blob, 2592), modulus);
		prod = mulmod(prod, basic_marshalling.get_uint256_be(blob, 2624), modulus);
		sum = addmod(sum, prod, modulus);
		prod = basic_marshalling.get_uint256_be(blob, 2560);
		prod = mulmod(prod, basic_marshalling.get_uint256_be(blob, 2624), modulus);
		sum = addmod(sum, prod, modulus);
		gate = addmod(gate, mulmod(theta_acc, sum, modulus), modulus);
		theta_acc = mulmod(theta_acc, theta, modulus);
		sum = 0;
		prod = basic_marshalling.get_uint256_be(blob, 2592);
		prod = mulmod(prod, basic_marshalling.get_uint256_be(blob, 2656), modulus);
		sum = addmod(sum, prod, modulus);
		prod = 28948022309329048855892746252171976963363056481941560715954676764349967630336;
		prod = mulmod(prod, basic_marshalling.get_uint256_be(blob, 2560), modulus);
		prod = mulmod(prod, basic_marshalling.get_uint256_be(blob, 2656), modulus);
		sum = addmod(sum, prod, modulus);
		prod = basic_marshalling.get_uint256_be(blob, 2624);
		prod = mulmod(prod, basic_marshalling.get_uint256_be(blob, 2656), modulus);
		sum = addmod(sum, prod, modulus);
		gate = addmod(gate, mulmod(theta_acc, sum, modulus), modulus);
		theta_acc = mulmod(theta_acc, theta, modulus);
		gate = mulmod(gate, basic_marshalling.get_uint256_be(blob, 384), modulus);
		F = addmod(F, gate, modulus);


    }
}        