
// SPDX-License-Identifier: Apache-2.0.
//---------------------------------------------------------------------------//
// Copyright (c) 2023 Generated by ZKLLVM-transpiler
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//---------------------------------------------------------------------------//
pragma solidity >=0.8.4;

import "@nilfoundation/evm-placeholder-verification/contracts/cryptography/transcript.sol";
import "@nilfoundation/evm-placeholder-verification/contracts/interfaces/modular_commitment.sol";
// Move away unused structures from types.sol
import "@nilfoundation/evm-placeholder-verification/contracts/types.sol";
import "@nilfoundation/evm-placeholder-verification/contracts/basic_marshalling.sol";
import "@nilfoundation/evm-placeholder-verification/contracts/containers/merkle_verifier.sol";
import "@nilfoundation/evm-placeholder-verification/contracts/algebra/polynomial.sol";
import "hardhat/console.sol";

library modular_commitment_scheme_multiplication {
    uint256 constant modulus = 28948022309329048855892746252171976963363056481941560715954676764349967630337;
    uint64 constant batches_num = 4;
    uint256 constant r = 2;
    uint256 constant lambda = 9;
    uint256 constant D0_size = 8;
    uint256 constant max_degree = 7;
    uint256 constant D0_omega = 199455130043951077247265858823823987229570523056509026484192158816218200659;
    uint256 constant unique_points = 4;
    uint256 constant permutation_point = 2;
    uint256 constant quotient_point = 0;
    uint256 constant lookup_point = 1156;
    bytes constant   points_ids = hex"01010101010101010101010101010101010101010101010101010101010101010101010101010101010103030101010101010101010101010101010101010101010101010101010101010101010101010101010100000000000000000000000000000000";
    uint256 constant omega = 199455130043951077247265858823823987229570523056509026484192158816218200659;
    uint256 constant _etha = 14966011778331694975342086510766377817344205817339978375739005187043951837846;

    struct commitment_state{
        bytes   leaf_data;
        uint256 roots_offset;
        uint256 initial_data_offset;
        uint256 initial_proof_offset;
        uint256 round_proof_offset;
        uint256 round_data_offset;
        uint256[r]  alphas;
        uint64[batches_num] batch_sizes;
        uint64 poly_num;
        uint256 points_num;
        uint256 theta;
        uint256 x_index;
        uint256 x;
        uint256 max_batch;
        uint256 domain_size;
        uint256[] final_polynomial;
        uint256 leaf_length;
        uint256[][unique_points] denominators;
        uint256[unique_points] factors;
        uint256[][unique_points] combined_U;
        uint256[][unique_points] unique_eval_points;
        uint256[2] y;
        uint256 j;
        uint256 offset;
    }

    function calculate_2points_interpolation(uint256[] memory xi, uint256[2] memory z)
    internal pure returns(uint256[2] memory U){
//        require( xi.length == 2 );
unchecked {
        U[0] = addmod(mulmod(z[0], xi[1], modulus),modulus - mulmod(z[1], xi[0], modulus), modulus);
        U[1] = addmod(z[1], modulus - z[0], modulus);
}
    }

//  coeffs for zs on each degree can be precomputed if necessary
    function calculate_3points_interpolation(uint256[] memory xi, uint256[3] memory z)
    internal pure returns(uint256[3] memory U){
//        require( xi.length == 3 );
unchecked {
        z[0] = mulmod(z[0], addmod(xi[1], modulus - xi[2], modulus), modulus);
        z[1] = mulmod(z[1], addmod(xi[2], modulus - xi[0], modulus), modulus);
        z[2] = mulmod(z[2], addmod(xi[0], modulus - xi[1], modulus), modulus);

        U[0] = mulmod(z[0], mulmod(xi[1], xi[2], modulus), modulus);
        U[0] = addmod(U[0], mulmod(z[1], mulmod(xi[0], xi[2], modulus), modulus), modulus);
        U[0] = addmod(U[0], mulmod(z[2], mulmod(xi[0], xi[1], modulus), modulus), modulus);

        U[1] = modulus - mulmod(z[0], addmod(xi[1], xi[2], modulus), modulus);
        U[1] = addmod(U[1], modulus - mulmod(z[1], addmod(xi[0], xi[2], modulus), modulus), modulus);
        U[1] = addmod(U[1], modulus - mulmod(z[2], addmod(xi[0], xi[1], modulus), modulus), modulus);

        U[2] = addmod(z[0], addmod(z[1], z[2], modulus), modulus);
}
    }

    function prepare_eval_points(uint256[][unique_points] memory result, uint256 xi) internal view {
        uint256 inversed_omega = field.inverse_static(omega, modulus);
		 result[0] = new uint256[](1);
		 result[0][0] = xi;
		 result[1] = new uint256[](2);
		 result[1][0] = xi;
		 result[1][1] = _etha;
		 result[2] = new uint256[](2);
		 result[2][0] = xi;
		 result[2][1] = mulmod(xi, omega, modulus);
		 result[3] = new uint256[](3);
		 result[3][0] = xi;
		 result[3][1] = mulmod(xi, omega, modulus);
		 result[3][2] = _etha;

    }

    function prepare_U_V(bytes calldata blob, commitment_state memory state, uint256 xi) internal view returns(bool result){

unchecked {
        result = true;
        uint64 ind = 0;
        prepare_eval_points(state.unique_eval_points, xi);
                // Prepare denominators
        for( ind = 0; ind < state.unique_eval_points.length;){
            state.denominators[ind] = new uint256[](state.unique_eval_points[ind].length + 1);
            if( state.unique_eval_points[ind].length == 1 ){
                state.factors[ind] = 1;
                state.denominators[ind][0] = modulus - state.unique_eval_points[ind][0];
                state.denominators[ind][1] = 1;
            } else
            if( state.unique_eval_points[ind].length == 2 ){
                // xi1 - xi0
                state.factors[ind] =
                    addmod(state.unique_eval_points[ind][1], modulus - state.unique_eval_points[ind][0], modulus);
                state.denominators[ind][2] = 1;

                state.denominators[ind][1] =
                    modulus - addmod(state.unique_eval_points[ind][0], state.unique_eval_points[ind][1], modulus);

                state.denominators[ind][0] =
                    mulmod(state.unique_eval_points[ind][0], state.unique_eval_points[ind][1], modulus);
                state.denominators[ind][0] = mulmod(state.denominators[ind][0], state.factors[ind], modulus);
                state.denominators[ind][1] = mulmod(state.denominators[ind][1], state.factors[ind], modulus);
                state.denominators[ind][2] = mulmod(state.denominators[ind][2], state.factors[ind], modulus);
            } else
            if( state.unique_eval_points[ind].length == 3 ){
                state.factors[ind] = modulus -
                    mulmod(
                        mulmod(
                            addmod(state.unique_eval_points[ind][0], modulus - state.unique_eval_points[ind][1], modulus),
                            addmod(state.unique_eval_points[ind][1], modulus - state.unique_eval_points[ind][2], modulus),
                            modulus
                        ),
                        addmod(state.unique_eval_points[ind][2], modulus - state.unique_eval_points[ind][0], modulus),
                        modulus
                    );
                state.denominators[ind][3] = 1;
                state.denominators[ind][2] =
                    modulus - addmod(
                        state.unique_eval_points[ind][0],
                        addmod(state.unique_eval_points[ind][1],state.unique_eval_points[ind][2], modulus),
                        modulus
                    );
                state.denominators[ind][1] =
                    addmod(
                        mulmod(state.unique_eval_points[ind][0], state.unique_eval_points[ind][1], modulus),
                        addmod(
                            mulmod(state.unique_eval_points[ind][0], state.unique_eval_points[ind][2], modulus),
                            mulmod(state.unique_eval_points[ind][1], state.unique_eval_points[ind][2], modulus),
                            modulus
                        ),
                        modulus
                    );
                state.denominators[ind][0] =
                    modulus - mulmod(
                        state.unique_eval_points[ind][0],
                        mulmod(state.unique_eval_points[ind][1],state.unique_eval_points[ind][2], modulus),
                        modulus
                    );
                state.denominators[ind][0] = mulmod(state.denominators[ind][0], state.factors[ind], modulus);
                state.denominators[ind][1] = mulmod(state.denominators[ind][1], state.factors[ind], modulus);
                state.denominators[ind][2] = mulmod(state.denominators[ind][2], state.factors[ind], modulus);
                state.denominators[ind][3] = mulmod(state.denominators[ind][3], state.factors[ind], modulus);
            } else {
                console.log("UNPROCESSED number of evaluation points");
                return false;
            }
            ind++;
        }

        // Prepare combined U
        for( uint256 ind = 0; ind < unique_points;){
            uint256[] memory point = state.unique_eval_points[ind];
            state.combined_U[ind] = new uint256[](state.unique_eval_points[ind].length);
            uint64 cur = 0;
            uint256 offset = 0x8;
            for( uint256 k = 0; k < batches_num;){
                for( uint256 i = 0; i < state.batch_sizes[k];){
                    uint256 cur_point = 0;
                    if(cur < points_ids.length ) cur_point = uint8(points_ids[cur]);
                    else if(k == 2) cur_point = permutation_point;
                    else if(k == 3) cur_point = quotient_point;
                    else if(k == 4) cur_point = lookup_point;
                    else console.log("Wrong index");

                    polynomial.multiply_poly_on_coeff(
                        state.combined_U[ind],
                        state.theta,
                        modulus
                    );
                    if( cur_point == ind ){
                        if( point.length == 1 ){
                            state.combined_U[ind][0] = addmod(
                                state.combined_U[ind][0],
                                basic_marshalling.get_uint256_be(blob, offset),
                                modulus
                            );
                        }  else
                        if( point.length == 2 ){
                            uint256[2] memory tmp;
                            tmp[0] = basic_marshalling.get_uint256_be(blob, offset);
                            tmp[1] = basic_marshalling.get_uint256_be(blob, offset + 0x20);
                            tmp = calculate_2points_interpolation(
                                point, tmp);
                            state.combined_U[ind][0] = addmod(state.combined_U[ind][0], tmp[0], modulus);
                            state.combined_U[ind][1] = addmod(state.combined_U[ind][1], tmp[1], modulus);
                        } else
                        if( point.length == 3){
                            uint256[3] memory tmp;
                            tmp[0] = basic_marshalling.get_uint256_be(blob, offset);
                            tmp[1] = basic_marshalling.get_uint256_be(blob, offset + 0x20);
                            tmp[2] = basic_marshalling.get_uint256_be(blob, offset + 0x40);
                            tmp = calculate_3points_interpolation(
                                point, tmp);
                            state.combined_U[ind][0] = addmod(state.combined_U[ind][0], tmp[0], modulus);
                            state.combined_U[ind][1] = addmod(state.combined_U[ind][1], tmp[1], modulus);
                            state.combined_U[ind][2] = addmod(state.combined_U[ind][2], tmp[2], modulus);
                        } else {
                            return false;
                        }
                    }
                    offset += state.unique_eval_points[cur_point].length * 0x20;
                    i++;cur++;
                }
                k++;
            }
            ind++;
        }
}
    }

    function compute_combined_Q(bytes calldata blob,commitment_state memory state) internal view returns(uint256[2] memory y){

unchecked {
        uint256[2][unique_points] memory values;
        {
            uint256 offset = state.initial_data_offset - state.poly_num * 0x40; // Save initial data offset for future use;
            uint256 cur = 0;
            for(uint256 b = 0; b < batches_num;){
                for(uint256 j = 0; j < state.batch_sizes[b];){
                    uint256 cur_point = 0;
                    if(cur < points_ids.length ) cur_point = uint8(points_ids[cur]);
                    else if(b == 2) cur_point = permutation_point;
                    else if(b == 3) cur_point = quotient_point;
                    else if(b == 4) cur_point = lookup_point;
                    else console.log("Wrong index");

                    for(uint256 k = 0; k < unique_points; ){
                        values[k][0] = mulmod(values[k][0], state.theta, modulus);
                        values[k][1] = mulmod(values[k][1], state.theta, modulus);
                        k++;
                    }

                    values[cur_point][0] = addmod(values[cur_point][0], basic_marshalling.get_uint256_be(blob, offset), modulus);
                    values[cur_point][1] = addmod(values[cur_point][1], basic_marshalling.get_uint256_be(blob, offset + 0x20), modulus);
                    offset += 0x40;j++; cur++;
                }
                b++;
            }
        }
        for(uint256 p = 0; p < unique_points; ){
            uint256[2] memory tmp = values[p];
            tmp[0] = mulmod(tmp[0], state.factors[p], modulus);
            tmp[1] = mulmod(tmp[1], state.factors[p], modulus);
            uint256 s = state.x;
            tmp[0] = addmod(tmp[0], modulus - polynomial.evaluate(state.combined_U[p], s , modulus), modulus);
            tmp[1] = addmod(tmp[1], modulus - polynomial.evaluate(state.combined_U[p], modulus - s, modulus), modulus);
            tmp[0] = mulmod(tmp[0], field.inverse_static(polynomial.evaluate(state.denominators[p], s, modulus), modulus), modulus);
            tmp[1] = mulmod(tmp[1], field.inverse_static(polynomial.evaluate(state.denominators[p], modulus - s, modulus), modulus), modulus);
            y[0] = addmod(y[0], tmp[0], modulus);
            y[1] = addmod(y[1], tmp[1], modulus);
            p++;
        }
}
    }

    function initialize(
        bytes32 tr_state_before
    ) internal returns(bytes32 tr_state_after){
        types.transcript_data memory tr_state;
        tr_state.current_challenge = tr_state_before;
        uint256 etha = transcript.get_field_challenge(tr_state, modulus);
        require(etha == _etha, "Wrong etha");
        tr_state_after = tr_state.current_challenge;
    }

    function copy_memory_pair_and_check(bytes calldata blob, uint256 proof_offset, bytes memory leaf, uint256[2] memory pair)
    internal pure returns(bool b){
        uint256 c = pair[0];
        uint256 d = pair[1];
        assembly{
            mstore(
                add(leaf, 0x20),
                c
            )
            mstore(
                add(leaf, 0x40),
                d
            )
        }
        if( !merkle_verifier.parse_verify_merkle_proof_bytes_be(blob, proof_offset, leaf, 0x40 )){
            return false;
        } else {
            return true;
        }
    }

    function copy_reverted_memory_pair_and_check(bytes calldata blob, uint256 proof_offset, bytes memory leaf, uint256[2] memory pair)
    internal pure returns(bool b){
        uint256 c = pair[0];
        uint256 d = pair[1];
        assembly{
            mstore(
                add(leaf, 0x20),
                d
            )
            mstore(
                add(leaf, 0x40),
                c
            )
        }
        if( !merkle_verifier.parse_verify_merkle_proof_bytes_be(blob, proof_offset, leaf, 0x40 )){
            return false;
        } else {
            return true;
        }
    }

    function copy_pairs_and_check(bytes calldata blob, uint256 offset, bytes memory leaf, uint256 size, uint256 proof_offset)
    internal pure returns(bool b){
unchecked {
        uint256 offset2 = 0x20;
        for(uint256 k = 0; k < size;){
            assembly{
                mstore(
                    add(leaf, offset2),
                    calldataload(add(blob.offset, offset))
                )
                mstore(
                    add(leaf, add(offset2, 0x20)),
                    calldataload(add(blob.offset, add(offset, 0x20)))
                )
            }
            k++; offset2 += 0x40; offset += 0x40;
        }
        if( !merkle_verifier.parse_verify_merkle_proof_bytes_be(blob, proof_offset, leaf, offset2 - 0x20 )){
            return false;
        } else {
            return true;
        }
}
    }

    function copy_reverted_pairs_and_check(bytes calldata blob, uint256 offset, bytes memory leaf, uint256 size, uint256 proof_offset)
    internal pure returns(bool){
unchecked {
        uint256 offset2 = 0x20;
        for(uint256 k = 0; k < size;){
            assembly{
                mstore(
                    add(leaf, offset2),
                    calldataload(add(blob.offset, add(offset, 0x20)))
                )
                mstore(
                    add(leaf, add(offset2, 0x20)),
                    calldataload(add(blob.offset, offset))
                )
            }
            k++; offset2 += 0x40; offset += 0x40;
        }
        if( !merkle_verifier.parse_verify_merkle_proof_bytes_be(blob, proof_offset, leaf, offset2 - 0x20 )){
            return false;
        } else {
            return true;
        }
}
    }

    function colinear_check(uint256 x, uint256[2] memory y, uint256 alpha, uint256 colinear_value) internal pure returns(bool){

unchecked {
        uint256 tmp;
        tmp = addmod(y[0], y[1], modulus);
        tmp = mulmod(tmp, x, modulus);
        tmp = addmod(
            tmp,
            mulmod(
                alpha,
                addmod(y[0], modulus-y[1], modulus),
                modulus
            ),
            modulus
        );
        uint256 tmp1 = mulmod(colinear_value , 2, modulus);
        tmp1 = mulmod(tmp1 , x, modulus);
        if( tmp !=  tmp1 ){
            console.log("Colinear check failed");
            return false;
        }
        return true;
}
    }

    function verify_eval(
        bytes calldata blob,
        uint256[5] memory commitments,
        uint256 challenge,
        bytes32 transcript_state
    ) internal view returns (bool){

unchecked {
        types.transcript_data memory tr_state;
        tr_state.current_challenge = transcript_state;
        commitment_state memory state;

        		{
			uint256 poly_at_eta;
			/* 1 - 2*permutation_size */
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 40);// 0
			if(poly_at_eta != 0x2116766564fcd93bd260d2d8d1564bd599ed931d3571b21df9c5971ca43b0296) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x68);// 0x1
			if(poly_at_eta != 0x25704ffaf8f03e2b1be41e3c16af7b2bbd16ad99f89e885eae8191b535270cec) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xa8);// 0x2
			if(poly_at_eta != 0x3b318fe6dcb136d78b74972c716d67da6ce43209c87eb7a2362d76b009c3409a) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xe8);// 0x3
			if(poly_at_eta != 0x27f7cf824f761235b946f3de37230743975a9640c545b1bcaa2e8dbc30d042fe) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x128);// 0x4
			if(poly_at_eta != 0x7d70d8b8d4e5b0c9e62c35713af24518df1244fbe758d5c876131e5f4114ef3) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x168);// 0x5
			if(poly_at_eta != 0x273343b9c287c73f17edd0b3626bb597c5b5b58eb84bc2cea4e5f97dc4568abf) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x1a8);// 0x6
			if(poly_at_eta != 0x40052a0cca6e43b77a51380ec1a8bf675b8c0d57d93e2b66cf64cadd5b0b5b8) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x1e8);// 0x7
			if(poly_at_eta != 0x14019d23ff427529563961849c84bbd04c9bc42b73e36d9020cf7f652c738c98) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x228);// 0x8
			if(poly_at_eta != 0x240811b3fc4c49ceaf1ee7970e97ab115cc43bdd3a242ab50ae04c0cde41bef7) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x268);// 0x9
			if(poly_at_eta != 0x34285883ed7d71096b9a85f348f657568b47f95a101ae35204071a665748bad1) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x2a8);// 0xa
			if(poly_at_eta != 0x4c9ba93a373352f1a049dc06ccfb4b02f4d7ad22b528c2baf6ec04bb46ba611) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x2e8);// 0xb
			if(poly_at_eta != 0x17f0a4e2314009eb821714c2200e8770ec83661ad89cbcda6d29c17a861a3e55) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x328);// 0xc
			if(poly_at_eta != 0x37b3386af64031998a7367caa048a5347c4a658a31c2b72888a396779e8337a8) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x368);// 0xd
			if(poly_at_eta != 0x16801a16cf40f7ffb44106f5216b3a05e45997c2d399af5c467d2ca218901644) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x3a8);// 0xe
			if(poly_at_eta != 0x308082720c44d7fe854522c9a718221d53795dd218b373b1c744ae3d7ad06f53) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x3e8);// 0xf
			if(poly_at_eta != 0x32828c3a3d5837f89a59adf04378aa923a8b0a265f9a572618cfd46c66122c9c) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x428);// 0x10
			if(poly_at_eta != 0x3c8cbd2332b917db03c065b1515b54dabde367cbc21cc86bb0879356fe5adf09) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x468);// 0x11
			if(poly_at_eta != 0x2ebfb1affd9d774712c1fc7696c8a8452c56a30aa55c05ac0df11cfef7c65b29) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x4a8);// 0x12
			if(poly_at_eta != 0x29be786ff41354635dc9ee50f1eb495976dd64411ee531097a2dfe33d6dfc7ca) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x4e8);// 0x13
			if(poly_at_eta != 0x10b85a2fc460a5f0d4f1a794b9986ebeeb7f2a517e9309dc975e643c325ee6ef) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x528);// 0x14
			if(poly_at_eta != 0x1399c2eed5e33db428b845e79ffa29ba77353a9b6f9238335baac43ffbda82aa) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x568);// 0x15
			if(poly_at_eta != 0x2cf510a4feb71e27e536714d534fba53a190ea958abe4cdbd93e9c609bccf23) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x5a8);// 0x16
			if(poly_at_eta != 0x1901bb0e707e55468b439493e1e92e739f96307442123f1f116d840e8e4032d0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x5e8);// 0x17
			if(poly_at_eta != 0x289025f78d6f5614e4004e394ecfa80cb8db0909c63c5cfdfec15254792b05b3) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x628);// 0x18
			if(poly_at_eta != 0x2e8b8712ba154da8927742dcec1dcf82b0b7f0ebe6c6ce0cc19cc5ec917d1a7f) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x668);// 0x19
			if(poly_at_eta != 0x7d70d8b8d4e5b0c9e62c35713af24518df1244fbe758d5c876131e5f4114ef3) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x6a8);// 0x1a
			if(poly_at_eta != 0x273343b9c287c73f17edd0b3626bb597c5b5b58eb84bc2cea4e5f97dc4568abf) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x6e8);// 0x1b
			if(poly_at_eta != 0x40052a0cca6e43b77a51380ec1a8bf675b8c0d57d93e2b66cf64cadd5b0b5b8) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x728);// 0x1c
			if(poly_at_eta != 0x14019d23ff427529563961849c84bbd04c9bc42b73e36d9020cf7f652c738c98) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x768);// 0x1d
			if(poly_at_eta != 0x240811b3fc4c49ceaf1ee7970e97ab115cc43bdd3a242ab50ae04c0cde41bef7) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x7a8);// 0x1e
			if(poly_at_eta != 0x34285883ed7d71096b9a85f348f657568b47f95a101ae35204071a665748bad1) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x7e8);// 0x1f
			if(poly_at_eta != 0x4c9ba93a373352f1a049dc06ccfb4b02f4d7ad22b528c2baf6ec04bb46ba611) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x828);// 0x20
			if(poly_at_eta != 0x17f0a4e2314009eb821714c2200e8770ec83661ad89cbcda6d29c17a861a3e55) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x868);// 0x21
			if(poly_at_eta != 0x37b3386af64031998a7367caa048a5347c4a658a31c2b72888a396779e8337a8) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x8a8);// 0x22
			if(poly_at_eta != 0x16801a16cf40f7ffb44106f5216b3a05e45997c2d399af5c467d2ca218901644) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x8e8);// 0x23
			if(poly_at_eta != 0x308082720c44d7fe854522c9a718221d53795dd218b373b1c744ae3d7ad06f53) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x928);// 0x24
			if(poly_at_eta != 0x21039d15b975951f065097386a1e3ab6b92f489261892c14298da023be164163) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x968);// 0x25
			if(poly_at_eta != 0x3c8cbd2332b917db03c065b1515b54dabde367cbc21cc86bb0879356fe5adf09) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x9a8);// 0x26
			if(poly_at_eta != 0x1aa2b43b1b44ec6fa2b312bcb09067dc8803564ec656f434a74407aa8bdc0c89) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x9e8);// 0x27
			if(poly_at_eta != 0x29be786ff41354635dc9ee50f1eb495976dd64411ee531097a2dfe33d6dfc7ca) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xa28);// 0x28
			if(poly_at_eta != 0x10b85a2fc460a5f0d4f1a794b9986ebeeb7f2a517e9309dc975e643c325ee6ef) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xa68);// 0x29
			if(poly_at_eta != 0x1399c2eed5e33db428b845e79ffa29ba77353a9b6f9238335baac43ffbda82aa) return false;
			/* 2 - special selectors */
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xac8);// 0x2a
			if(poly_at_eta != 0x3d3df6b82b09a0ce58da45ff8759b8fa6b0d2973fc7c4242c6d8912d97aacb12) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xb28);// 0x2b
			if(poly_at_eta != 0x2cbfccb6d57a5072a13e36a6f309b3e71e88318483e6f2c300602d26b865098d) return false;
			/* 3 - constant columns */
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xb68);// 0x2c
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xba8);// 0x2d
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xbe8);// 0x2e
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xc28);// 0x2f
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xc68);// 0x30
			if(poly_at_eta != 0x0) return false;
			/* 4 - selector columns */
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xca8);// 0x31
			if(poly_at_eta != 0x9194e34992d67cc6907469156236a8d07c1ce9fd0920a66ee51a9631354e0d8) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xce8);// 0x32
			if(poly_at_eta != 0x22341321b125fb8f959a3671049eec657be05e4f8469491ca602b139e2d444e2) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xd28);// 0x33
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xd68);// 0x34
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xda8);// 0x35
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xde8);// 0x36
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xe28);// 0x37
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xe68);// 0x38
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xea8);// 0x39
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xee8);// 0x3a
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xf28);// 0x3b
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xf68);// 0x3c
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xfa8);// 0x3d
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0xfe8);// 0x3e
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x1028);// 0x3f
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x1068);// 0x40
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x10a8);// 0x41
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x10e8);// 0x42
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x1128);// 0x43
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x1168);// 0x44
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x11a8);// 0x45
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x11e8);// 0x46
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x1228);// 0x47
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x1268);// 0x48
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x12a8);// 0x49
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x12e8);// 0x4a
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x1328);// 0x4b
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x1368);// 0x4c
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x13a8);// 0x4d
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x13e8);// 0x4e
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x1428);// 0x4f
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x1468);// 0x50
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x14a8);// 0x51
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x14e8);// 0x52
			if(poly_at_eta != 0x0) return false;
			poly_at_eta = basic_marshalling.get_uint256_be(blob, 0x1528);// 0x53
			if(poly_at_eta != 0x0) return false;
		}


        {
            uint256 offset;

            if (challenge!= transcript.get_field_challenge(tr_state, modulus)) return false;

            for(uint8 i = 0; i < batches_num;){
                transcript.update_transcript_b32(tr_state, bytes32(commitments[i]));
                i++;
            }
            state.theta = transcript.get_field_challenge(tr_state, modulus);

            state.points_num = basic_marshalling.get_length(blob, 0x0);
            offset = 0x8 + state.points_num*0x20 + 0x8;
            for(uint8 i = 0; i < batches_num;){
                state.batch_sizes[i] = uint64(uint8(blob[offset + 0x1]));
                if( state.batch_sizes[i] > state.max_batch ) state.max_batch = state.batch_sizes[i];
                state.poly_num += state.batch_sizes[i];
                i++; offset +=2;
            }

            offset += 0x8;
            offset += state.poly_num;
            state.roots_offset = offset + 0x8;
            offset += 0x8;

            for( uint8 i = 0; i < r;){
                transcript.update_transcript_b32(tr_state, bytes32(basic_marshalling.get_uint256_be(blob, offset + 0x8)));
                state.alphas[i] = transcript.get_field_challenge(tr_state, modulus);
                i++; offset +=40;
            }

            

            offset += 0x8 + r;
            state.initial_data_offset = offset + 0x8;
            offset += 0x8 + 0x20*basic_marshalling.get_length(blob, offset);

            state.round_data_offset = offset + 0x8;
            offset += 0x8 + 0x20*basic_marshalling.get_length(blob, offset);
            offset += 0x8;

            state.initial_proof_offset = offset;
            for(uint8 i = 0; i < lambda;){
                for(uint j = 0; j < batches_num;){
                    if(basic_marshalling.get_uint256_be(blob, offset + 0x10) != commitments[j] ) return false;
                    offset = merkle_verifier.skip_merkle_proof_be(blob, offset);
                    j++;
                }
                i++;
            }
            offset += 0x8;
            state.round_proof_offset = offset;

            for(uint256 i = 0; i < lambda;){
                for(uint256 j = 0; j < r;){
                    if(basic_marshalling.get_uint256_be(blob, offset + 0x10) != basic_marshalling.get_uint256_be(blob, state.roots_offset + j * 40 + 0x8) ) return false;
                    offset = merkle_verifier.skip_merkle_proof_be(blob, offset);
                    j++;
                }
                i++;
            }

            state.final_polynomial = new uint256[](basic_marshalling.get_length(blob, offset));
            offset += 0x8;
            for (uint256 i = 0; i < state.final_polynomial.length;) {
                state.final_polynomial[i] = basic_marshalling.get_uint256_be(blob, offset);
                i++; offset+=0x20;
            }
        }
        if( state.final_polynomial.length > (( 1 << (field.log2(max_degree + 1) - r + 1) ) ) ){
            console.log("Wrong final poly degree");
            return false;
        }

        if( !prepare_U_V(blob, state, challenge) ) return false;

        state.leaf_data = new bytes(state.max_batch * 0x40 + 0x40);
        for(uint256 i = 0; i < lambda;){
            // Initial proofs
            state.x_index = uint256(transcript.get_integral_challenge_be(tr_state, 8))  % D0_size;
            state.x = field.pow_small(D0_omega, state.x_index, modulus);
            state.domain_size = D0_size >> 1;
            for(uint256 j = 0; j < batches_num;){
                if( state.x_index < state.domain_size ){
                    if(!copy_pairs_and_check(blob, state.initial_data_offset, state.leaf_data, state.batch_sizes[j], state.initial_proof_offset)){
                        console.log("Error in initial mekle proof");
                        return false;
                    }
                } else {
                    if(!copy_reverted_pairs_and_check(blob, state.initial_data_offset, state.leaf_data, state.batch_sizes[j], state.initial_proof_offset)){
                        console.log("Error in initial mekle proof");
                        return false;
                    }
                }
                state.leaf_length = state.batch_sizes[j] * 0x40;
                state.initial_data_offset += state.batch_sizes[j] * 0x40;
                state.initial_proof_offset = merkle_verifier.skip_merkle_proof_be(blob, state.initial_proof_offset);
                j++;
            }
            {
                state.y = compute_combined_Q(blob, state);
                if( state.x_index < state.domain_size ){
                    if( !copy_memory_pair_and_check(blob, state.round_proof_offset, state.leaf_data, state.y) ){
                        console.log("Not validated!");
                        return false;
                    }
                }else{
                    if( !copy_reverted_memory_pair_and_check(blob, state.round_proof_offset, state.leaf_data, state.y) ){
                        console.log("Not validated!");
                        return false;
                    }
                }
            }
            if( !colinear_check(state.x, state.y, state.alphas[0], basic_marshalling.get_uint256_be(blob,state.round_data_offset)) ){
                console.log("Colinear check failed");
                return false;
            }

            state.round_proof_offset = merkle_verifier.skip_merkle_proof_be(blob, state.round_proof_offset);
            for(state.j = 1; state.j < r;){
                state.x_index %= state.domain_size;
                state.x = mulmod(state.x, state.x, modulus);
                state.domain_size >>= 1;
                if( state.x_index < state.domain_size ){
                    if(!copy_pairs_and_check(blob, state.round_data_offset, state.leaf_data, 1, state.round_proof_offset)) {
                        console.log("Error in round mekle proof");
                        return false;
                    }
                } else {
                    if(!copy_reverted_pairs_and_check(blob, state.round_data_offset, state.leaf_data, 1, state.round_proof_offset)) {
                        console.log("Error in round mekle proof");
                        return false;
                    }
                }
                state.y[0] = basic_marshalling.get_uint256_be(blob, state.round_data_offset);
                state.y[1] = basic_marshalling.get_uint256_be(blob, state.round_data_offset + 0x20);
                if( !colinear_check(state.x, state.y, state.alphas[state.j], basic_marshalling.get_uint256_be(blob,state.round_data_offset + 0x40)) ){
                    console.log("Round colinear check failed");
                    return false;
                }
                state.j++; state.round_data_offset += 0x40;
                state.round_proof_offset = merkle_verifier.skip_merkle_proof_be(blob, state.round_proof_offset);
            }

            state.x = mulmod(state.x, state.x, modulus);
            if(polynomial.evaluate(state.final_polynomial, state.x, modulus) != basic_marshalling.get_uint256_be(blob, state.round_data_offset)) {
                console.log("Wrong final poly check");
                return false;
            }
            if(polynomial.evaluate(state.final_polynomial, modulus - state.x, modulus) != basic_marshalling.get_uint256_be(blob, state.round_data_offset + 0x20)){
                console.log("Wrong final poly check");
                return false;
            }
            state.round_data_offset += 0x40;

            i++;
        }
        return true;
}
    }
}
    